### ISSUE TITLE
date is not valid

### ISSUE THREAD

**Issue by prasanta352** [Rahim373/bangla-tarikh#1]
hey today is 14 April 2019 ৩০শে চৈত্র ১৪২৫
![2](https://user-images.githubusercontent.com/32667365/56096470-2fecc780-5f06-11e9-8612-b8d32931d2e4.png)
but your package is showing ১লা বৈশাখ ১৪২৬
![1](https://user-images.githubusercontent.com/32667365/56096469-2f543100-5f06-11e9-9cb2-e4c502dfab93.png)
could you see what is going on ?

**Comment by Rahim373** [comment]
In Bangladesh, 14th April is 1st of Baishakh. And Isn't it showing the right info?

**Comment by prasanta352** [comment]
No in India is 15 April 

Is Bangladesh and Indian Bengali calendar differs from each other ?

**Comment by Rahim373** [comment]
Yes. The dates differ in Bangladesh and India. Some references are given below for consideration,

- https://en.wikipedia.org/wiki/Pahela_Baishakh
- http://outscar.com/support/index.php/posts/bngla-tarikh-india-bd
 
I think I should rename the package name as it is working only for Bangladesh.

**Comment by prasanta352** [comment]
Ok thanks
